# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mus2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireNetworkActivityLogger', '~> 2.3'
  pod 'ObjectMapper', '~> 3.3'
  pod 'SwiftyJSON', '~> 4.0'

end
